docs/mechanism&algorithm/multi-signatures.md

add multi-signatures fees

---

docs/api/http.md
docs/api/rpc.md

add a description for getnewshieldedaddress

add description for getnewshieldedaddress

---

docs/api/http.md

the return of this interface getexpandedspendingkey is changed, update the document.

modify the Expanded spending keys

---

docs/architecture/network.md

Refactor the network document

---

docs/architecture/network.md

update the "wget" commands in section 3.2.1 and section 3.2.2
add one more steps in section 3.2.2(step 7)

docs: update the commands and add more steps in section 3.2.2

---

.github/workflows/gh-pages.yml

This PR allows for the code highlight.

ci: use newest pygments

---

docs/api/http.md

add api gettransactioninfobyblocknum

feat: add api gettransactioninfobyblocknum

---

docs/faq/index.md

- use headings
- add toc
See-also: https://github.com/tronprotocol/documentation-zh/pull/26

docs(faq): refine faq style

---

docs/api/http.md

Reverts tronprotocol/documentation-en#33
The feature hasn't released yet.

Revert "Revise api doc"

---

docs_without_index/mpc/093/README.md
docs_without_index/mpc/093/report.asc
docs_without_index/mpc/094/README.md
docs_without_index/mpc/094/report.asc
docs_without_index/mpc/095/README.md
docs_without_index/mpc/095/report.asc
docs_without_index/mpc/096/README.md
docs_without_index/mpc/096/report.asc
docs_without_index/mpc/097/README.md
docs_without_index/mpc/097/report.asc
docs_without_index/mpc/098/README.md
docs_without_index/mpc/098/report.asc
docs_without_index/mpc/099/README.md
docs_without_index/mpc/099/report.asc
docs_without_index/mpc/100/README.md
docs_without_index/mpc/100/report.asc
docs_without_index/mpc/randombeacon/README.md

1. add random beacon's contribution for mpc

add random beacon's contribution for mpc

---

docs/mechanism-algorithm/system-contracts.md

Add missing fields(system-contracts) for:
TriggerSmartContract
CreateSmartContract

Add missing fields

---

docs/introduction/overview.md
docs/mechanism-algorithm/resource.md
docs/mechanism-algorithm/sr.md

1. Bandwidth price 140 sun -> 1000 sun
2. Account creation fee 0 - > 1 trx
3. Removing Chinese descriptions

Adjustment of the description for bandwidth and account creation fees

---

docs/releases/index.md

Add shasum and signature for 4.3.0.

update(release): add signature for 4.3.0

---

docs/api/http.md

The request described previously did not work. I've tried to use GET instead of POST and all went well

Updated request method with the correct one

---

docs/index.md
mkdocs.yml

Getting Started with Java-tron

Getting Started with Java-tron

---

docs/clients/wallet-cli-command.md

previous doc about bancor is invalid, so we use the new link.

docs: update wallet-cli-command.md

---

docs/introduction/overview.md
docs/mechanism-algorithm/dex.md
docs/mechanism-algorithm/resource.md
docs/releases/history.md
docs/using_javatron/backup_restore.md

1. Modify the underline appearing in big numbers
2. Modify the location of ip address 35.197.17.205

Fix: underline in big number and location of an IP

---

.github/workflows/gh-pages.yml
docs/mechanism-algorithm/account.md
docs/mechanism-algorithm/multi-signatures.md
docs/using_javatron/backup_restore.md

1. Fix the doc of witness permission 
2. Fix the doc of operations of active permission
3. Fix the ip address of 34.143.247.77

Fix: Permission doc fix

---

.github/workflows/gh-pages.yml
mkdocs.yml

1.Remove files that are not in the nav and  files that have no dependency relationship with the files in the nav
2.Keep index.html

Fix: remove files not in nav of gh-pages

---

docs/mechanism-algorithm/multi-signatures.md
docs/using_javatron/private_network.md

There were some issues with the page display, so I made some modifications. It has been verified and can be merged directly.

Fix format for page

---

docs/api/json-rpc.md
docs/api/rpc.md
docs/mechanism-algorithm/sr.md
mkdocs.yml

1. add json-rpc doc
2. fix some md format

feat: add json-rpc doc

---

.github/workflows/gh-pages.yml
docs/javascripts/nav-toc.js
docs/javascripts/toc.js
docs/overrides/partials/toc-item.html
docs/stylesheets/extra.css
mkdocs.yml

1. change doc theme from readthedocs to material;
2. integrate toc to nav; change the toc default state to just display secondary title(begin with ##) of toc ;add expand and collapse function of toc by click to be consistent with the previous overall layout;
3. change the color style to be consistent with developers.tron.network

Feat: use material theme

---

README.md
docs/index.md
docs/introduction/index.md
docs/overrides/404.html
docs/overrides/base.html
docs/overrides/partials/footer.html
docs/stylesheets/extra.css
mkdocs.yml

1. remove old default footer, add custom footer
2. integrate valuable information of /documentation-en/introduction/index.md to /documentation-en/index.md，change the entrance in readme.md from /documentation-en/introduction/ to /documentation-en/(homepage)  , put /documentation-en/introduction/index.md into mkdocs-exclude list
3. add homepage link to 404.html

Feat: as description

---

docs/getting_started/getting_started_with_javatron.md
docs/using_javatron/backup_restore.md

1. Add nile testnet data snapshot
2. md format fix in getting_started/getting_started_with_javatron.md and using_javatron/backup_restore.md

Feat: Add nile testnet data snapshot and format fix 

---

docs/javascripts/nav-toc.js
docs/javascripts/toc.js

1. add link behavior of toc-item with children, the behavior is jumping to the location of toc-item in the page.
2. add link behavior of nav-item with nested toc when the toc is expanded, the behavior is jumping to top of the page.

Feat: add link behavior 

---

docs/architecture/database.md

Fix: database config

---

docs/mechanism-algorithm/system-contracts.md

Fix: ExchangeTransactionContract proto

---

docs/using_javatron/installing_javatron.md

Restructured the deployment documentation for improved clarity and readability.

docs(deployment): Refactor deployment guide
